[clang] Fix warnings
This patch fixes:

  clang/lib/Tooling/DependencyScanning/InProcessModuleCache.cpp:38:5:
  error: 'shared_lock' may not intend to support class template
  argument deduction [-Werror,-Wctad-maybe-unsupported]

  clang/lib/Tooling/DependencyScanning/InProcessModuleCache.cpp:68:7:
  error: 'lock_guard' may not intend to support class template
  argument deduction [-Werror,-Wctad-maybe-unsupported]

(cherry picked from commit 934ef305227ad4bd3d95c92e0f9cf1ad605ced9d)